Check for iwpriv command

diff --git a/system/xbin/mondis b/system/xbin/mondis
--- a/system/xbin/mondis
+++ b/system/xbin/mondis
@@ -9,6 +9,11 @@ if [ ! -e "/sys/module/wlan/parameters/con_mode" ]; then
 	exit 1
 fi
 
+if ! which iwpriv > /dev/null ; then
+        echo "iwpriv command not found"
+        exit 1
+fi
+
 # Shutdown gracefully
 iwpriv wlan0 monitor 0
 # Disable the interface
diff --git a/system/xbin/monen b/system/xbin/monen
--- a/system/xbin/monen
+++ b/system/xbin/monen
@@ -21,6 +21,11 @@ if [ ! -e "/sys/module/wlan/parameters/con_mode" ]; then
 	exit 1
 fi
 
+if ! which iwpriv > /dev/null ; then
+	echo "iwpriv command not found"
+	exit 1
+fi
+
 if [ "$#" -ne "0" ]; then
 	if [ "$#" -eq "5" ]; then
 		CONF=$@
